export const resourceslink = [
  // 576 changed to 579
  {
    id: 579,
    name: 'Spotify',
    description: 'Free 3-Months of Premium Music Streaming on Spotify. Student discount is also available.',
    validity: 'June 30',
    link: 'https://www.spotify.com/in/premium/',
    category: 'entertainment music spotify ',
  },
  {
    id: 575,
    name: 'FreeCodeCamp PyTorch',
    description: 'Deep Learning with PyTorch: Zero to GANs is a Free Certification Course. The course would be live on freeCodeCamp\'s Youtube every Saturday at 8.30 AM PST.',
    validity: 'May 23',
    link: 'http://bit.ly/pytorchcourse',
    category: 'edu machine learning machinelearning ml certificate',
  },
  {
    id: 500,
    name: 'Coursera',
    description: '115 Free Certificate Online Courses. Has good courses for Core Computer Science and Machine Learning.',
    validity: 'July 31',
    link: 'https://www.coursera.org/',
    category: 'education computerscience data science datascience',
  },
  {
    id: 501,
    name: 'Datacamp',
    description: 'Includes over 300 certificate courses exploring languages such as R and Python and diving into subjects such as machine learning.',
    validity: 'May 22',
    link: 'https://www.datacamp.com/community/blog/free-week',
    category: 'education datascience data science programming',
  },
  {
    id: 502,
    name: 'FutureLearn',
    description: '50+ Free Certificate Courses: Includes courses from institutions such as King’s College, University of Edinburgh, and Monash University.',
    validity: 'NA',
    link: 'https://www.classcentral.com/report/futurelearn-free-certificates/',
    category: 'education programming learning business',
  },
  {
    id: 503,
    name: 'FutureLearn',
    description: '16 Free Certificate Courses: Includes a wide variety of certificate courses from Australian universities.',
    validity: 'NA',
    link: 'https://www.futurelearn.com/courses/collections/study-australia',
    category: 'education programming learning business',
  },
  {
    id: 504,
    name: 'Skillshare',
    description: '2-Month Free Trial: Includes 2,000+ online courses in tech, business, and art.  Requires signing up with a credit card or PayPal, so cancel in time.',
    validity: 'NA',
    link: 'https://join.skillshare.com/bd-bombay-create-from-home/',
    category: 'education learning seo cooking productivity',
  },
  {
    id: 505,
    name: 'Great Learning',
    description: '70+ Free Certificate Courses: Includes courses on a wide variety of subjects such as artificial intelligence, data science, programming, and marketing.',
    validity: 'NA',
    link: 'https://www.greatlearning.in/academy/',
    category: 'education datascience business',
  },
  {
    id: 506,
    name: 'upGrad',
    description: '10 Free Tech Programs: Includes programs in data science, technology, and management.',
    validity: 'NA',
    link: 'https://www.upgrad.com/free-courses/',
    category: 'education python datascience',
  },
  {
    id: 507,
    name: 'Le Wagon',
    description: '20+ Hour Free Web Development Course: Covers the fundamentals of HTML and CSS, and walks you through each step of the creation of a website.',
    validity: 'August 31',
    link: 'http://honoris.net/learntocode/',
    category: 'education frontend backend javascript',
  },
  {
    id: 508,
    name: 'ICSI',
    description: 'Free Cybersecurity Program: Provides a holistic view of modern network security.',
    validity: 'May 31',
    link: 'https://www.icsi.co.uk/courses/icsi-cnss-certified-network-security-specialist-covid-19',
    category: 'education networking hacking',
  },
  {
    id: 509,
    name: 'Educative io',
    description: 'Free Front-End Development Courses: Covers the fundamentals of front-end web development, from HTML and CSS to JavaScript.',
    validity: 'NA',
    link: 'https://www.educative.io/covid-scholarship',
    category: 'education frontend backend ',
  },
  {
    id: 510,
    name: 'AppSumo',
    description: 'Access 12-minute summaries of some of the best business and personal development books.',
    validity: '1 Year',
    link: 'https://appsumo.com/readitforme/',
    category: 'education summary audio',
  },
  {
    id: 511,
    name: 'Netflix',
    description: '20+ Hours of Free Documentaries: Includes documentaries about nature, politics, society, and design. It doesn’t require sign-up',
    validity: 'NA',
    link: 'https://www.youtube.com/playlist?list=PLvahqwMqN4M0GRkZY8WkLZMb6Z-W7qbLA',
    category: 'entertainment movies chill',
  },
  {
    id: 512,
    name: 'Redis University',
    description: '60+ Hours of Free Redis Courses: Includes courses from Redis fundamentals. These are always free, but only temporarily available.',
    validity: 'May 21',
    link: 'https://redislabs.com/blog/redis-university-announces-self-paced-on-demand-courses/',
    category: 'education caching databases',
  },
  {
    id: 513,
    name: 'openHPI',
    description: '8 Free Certificate Courses: Includes courses on subjects such as computer science, data science, and blockchain. Almost all courses are in German.',
    validity: 'June 30',
    link: 'https://open.hpi.de/news?locale=en#post_d0c5a972-88f9-433c-a945-3651e2c53a9a',
    category: 'education datascience python',
  },
  {
    id: 514,
    name: 'SAP',
    description: '200+ Free Tech Courses: Includes courses on SAP software, computer science, and technology in general.',
    validity: 'NA',
    link: 'https://news.sap.com/2020/03/new-sap-digital-learning-initiative/',
    category: 'education',
  },
  {
    id: 515,
    name: 'EduCode Academy',
    description: 'Includes interactive courses to help kids, teens, and young adults learn how to program.',
    validity: 'May 31',
    link: 'https://educode.org/blog/2020/03/20/free-education-to-flatten-the-curve',
    category: 'education',
  },
  {
    id: 516,
    name: 'XYZ Coding',
    description: 'Includes courses to become a full-stack developer. Requires signing up with credit card, so cancel in time.',
    validity: 'May 23',
    link: 'https://xyzcoding.com/subscription/',
    category: 'education fullstack javascript python django mysql',
  },
  {
    id: 517,
    name: 'SAS',
    description: '1-Month Free Data Science Courses: Includes programs in AI and machine learning, data curation, and advanced analytics.',
    validity: 'NA',
    link: 'https://www.sas.com/en_us/news/press-releases/2020/april/sas-offers-free-online-learning.html',
    category: 'education datascience artificial intelligence machinelearning dataanalytics analysis',
  },
  {
    id: 518,
    name: 'Coding Blocks',
    description: '15+ Hours Free Competitive Programing Course: Covers various algorithms and coding competitions.',
    validity: 'May 31',
    link: 'https://online.codingblocks.com/courses/competitive-programming-question-solving',
    category: 'education python dynamic sorting',
  },
  {
    id: 519,
    name: 'App Brewery',
    description: '10+ Hours Free App Develpment Course: Covers app development in Flutter using the Dart programming language.',
    validity: 'July 8',
    link: 'https://www.appbrewery.co/p/intro-to-flutter',
    category: 'education angelayu',
  },
  {
    id: 520,
    name: 'General Assembly',
    description: '20+ Free Live Workshops: Includes workshops to learn marketing, programming, and data science.',
    validity: 'June 30',
    link: 'https://generalassemb.ly/blog/free-fridays/',
    category: 'education business datascience',
  },
  {
    id: 521,
    name: 'Nikon',
    description: '10 Free Photography Short Online Courses: Includes courses on photography fundamentals from domain experts.',
    validity: 'May 31',
    link: 'https://www.nikonevents.com/us/live/nikon-school-online/?fs=y',
    category: 'productivity camera',
  },
  {
    id: 522,
    name: 'BitDegree',
    description: '50+ Free Tech Online Courses: Includes gamified courses in programming, web development, and blockchain.',
    validity: 'NA',
    link: 'https://www.bitdegree.org/tag/covid',
    category: 'education webdevelopment frontend backend fullstack',
  },
  {
    id: 523,
    name: 'Rosetta Stone',
    description: '3 Months of Free Language Learning: Includes languages such as English, Spanish, and French.',
    validity: 'NA',
    link: 'https://www.rosettastone.com/freeforstudents/',
    category: 'education',
  },
  {
    id: 524,
    name: 'Google',
    description: '1-Month Free Trial to Google Cloud Training: Includes online courses via Coursera Specializations or Pluralsight Paths.',
    validity: 'May 31',
    link: 'https://inthecloud.withgoogle.com/training-discount/register.html',
    category: 'education engineer cloud devops',
  },
  {
    id: 525,
    name: 'IBM',
    description: '100+ Free IBM Training Courses: Includes courses about IBM’s Cloud and Watson platforms, and professional development in general.',
    validity: 'NA',
    link: 'https://www.ibm.com/blogs/ibm-training/free-training-to-update-skills/',
    category: 'education cloud',
  },
  {
    id: 526,
    name: 'Tableau',
    description: '3-Month Free Tableau Training: Includes courses exploring all facets of the data science software Tableau.',
    validity: '3 Months',
    link: 'https://www.tableau.com/learn/training/elearning',
    category: 'education datascience database machinelearning analytics',
  },
  {
    id: 527,
    name: 'Alteryx',
    description: '3-Month Alteryx Data Science Course License & 1-Month Udacity Predictive Analysis Nanodegree Access.',
    validity: 'NA',
    link: 'https://pages.alteryx.com/adapt?_ga=2.165896830.1543425575.1589166221-61802955.1589166221',
    category: 'education datascience machinelearning database analytics',
  },
  {
    id: 528,
    name: 'Teachable',
    description: 'Teachable has partnered with its creators and has made some courses free on its platform. Courses include Programming, Business, Cooking, etc.',
    validity: 'NA',
    link: 'https://discover.teachable.com/courses/free-courses',
    category: 'education SEO kitchen deal meditation digitalmarketing writing blender music piano businessintelligence',
  },
  {
    id: 529,
    name: 'Moz Academy',
    description: '25+ Free SEO Courses: Includes courses exploring all aspects of search engine optimization.',
    validity: 'NA',
    link: 'https://academy.moz.com/',
    category: 'education business marketing',
  },
  {
    id: 530,
    name: 'Product School',
    description: '10+ Hours of Free Product Management Courses: Includes a course on digital products and another on career development.',
    validity: 'NA',
    link: 'https://www.productschool.com/learn-from-home/',
    category: 'education business',
  },
  {
    id: 531,
    name: 'PPA',
    description: '1000+ Free Photography Short Courses: Includes courses from photography fundamentals to how to build a photography business.',
    validity: 'May 31',
    link: 'https://www.ppa.com/education-unlocked',
    category: 'education camera learning',
  },
  {
    id: 532,
    name: 'Project Management',
    description: '10+ Hours of Project Management Courses: Includes various resources, most notably, free online courses.',
    validity: 'NA',
    link: 'https://www.pmi.org/about/coronavirus-single-source-message/virtual-resource-hub',
    category: 'education businessmanagement',
  },
  {
    id: 533,
    name: 'Young Screenwriters',
    description: 'Free Screenwriting Course: Covers the fundamentals of screenwriting.',
    validity: 'NA',
    link: 'https://youngscreenwriters.teachable.com/p/writing-the-short',
    category: 'education screenplay moviewriting',
  },
  {
    id: 534,
    name: 'Domestika',
    description: '20+ Free Creative Online Courses: Includes courses in drawing, photography, and design.',
    validity: 'NA',
    link: 'https://www.domestika.org/stayathome/',
    category: 'education arts crafts',
  },
  {
    id: 535,
    name: 'HomeSchoolPiano',
    description: '10+ Hours of Free Piano Lessons: Includes access to video lessons about piano fundamentals as well as live practice sessions.',
    validity: 'August 31',
    link: 'https://homeschoolpiano.com/give-back/',
    category: 'education music',
  },
  {
    id: 536,
    name: 'Fender',
    description: 'Free Guitar Lessons: Includes guitar (acoustic or electric), bass, and ukulele video lessons. Valid in a few countries only.',
    validity: 'May 31',
    link: 'https://try.fender.com/play/playthrough/',
    category: 'entertainment music',
  },
  {
    id: 537,
    name: 'Producertech',
    description: '3-Month Free Trial: Includes 400+ hours of courses to learn music production. Requires signing up with a credit card or PayPal, so cancel in time.',
    validity: 'NA',
    link: 'https://www.producertech.com/blog/stayincreate-with-producertech-loopmasters-and-plugin-boutique',
    category: 'education',
  },
  {
    id: 538,
    name: 'Creativebug',
    description: '2-Month Free Trial: Includes 1000+ arts and crafts online classes. Requires signing up with a credit card or PayPal, so cancel in time.',
    validity: 'NA',
    link: 'https://www.creativebug.com/trial/create-account?theme=joann60&sscid=51k4_c6f2',
    category: 'productivitytools drawing artist creativity',
  },
  {
    id: 539,
    name: 'Milk Street',
    description: '10+ Free Cooking Classes: Includes access to online classes covering cooking fundamentals as well as specific recipes.',
    validity: 'May 31',
    link: 'https://www.177milkstreet.com/school/classes/online-classes/',
    category: 'productivity recipies',
  },
  // changed 540 to 600
  {
    id: 600,
    name: 'Packt',
    description: '15 Free Tech Certificate Courses: Includes one-year access to practical online courses covering notably Python, JavaScript, and Machine Learning.',
    validity: 'May 31',
    link: 'https://courses.packtpub.com/pages/free',
    category: 'education fullstackwebdevelopment machinelearning datascience sql dataanalytics',
  },
  {
    id: 541,
    name: 'Springer',
    description: '500+ Free E-Books: Includes e-books on subjects such as nature, machine learning, and data science.',
    validity: 'July 31',
    link: 'https://www.springernature.com/gp/librarians/news-events/all-news-articles/industry-news-initiatives/free-access-to-textbooks-for-institutions-affected-by-coronaviru/17855960',
    category: 'education datascience machinelearning bigdata',
  },
  {
    id: 542,
    name: 'ACM Digital Library',
    description: 'Free Full Platform Access: Hosts articles, magazines, and conference proceedings published by the Association for Computing Machinery.',
    validity: 'June 30',
    link: 'https://www.acm.org/articles/bulletins/2020/march/dl-access-during-covid-19',
    category: 'education learning books journals',
  },
  {
    id: 543,
    name: 'Annual Reviews',
    description: 'Free Full Platform Access: Hosts a collection of journals dedicated to disciplines ranging from anthropology to virology.',
    validity: 'June 15',
    link: 'https://annualreviewsnews.org/2020/03/13/annual-reviews-removes-access-control-in-response-to-covid-19-pandemic/',
    category: 'education papers',
  },
  {
    id: 544,
    name: 'Scitation',
    description: 'Free Full Platform Access: Hosts academic articles and journals published by the American Institute of Physics.',
    validity: 'NA',
    link: 'https://www.scitation.org/remote-access',
    category: 'education researchjournal',
  },
  {
    id: 545,
    name: 'Internet Archive',
    description: '1.3 Million E-Books with Instant Access: Includes a wide collection of digitized books with a focus on 20th century literature.',
    validity: 'June 31',
    link: 'https://archive.org/details/nationalemergencylibrary',
    category: 'education books library learning journals',
  },
  {
    id: 546,
    name: 'Unity',
    description: 'Free Full Platform Access: Offers 350+ hours worth of educational content about the Unity game engine.',
    validity: 'June 20',
    link: 'https://learn.unity.com/',
    category: 'education gaming c# programming gamedevelopment',
  },
  {
    id: 547,
    name: 'Autopsy',
    description: 'Free Intro to Autopsy (Digital Forensics Software): Includes 8 hours of video lessons.',
    validity: 'June 1',
    link: 'https://www.autopsy.com/support/training/covid-19-free-autopsy-training/',
    category: 'education',
  },
  {
    id: 548,
    name: 'Elastic',
    description: '20-Hours of Free Elastic Courses: Includes a series of courses on various aspects of the Elastic Stack.',
    validity: 'NA',
    link: 'https://training.elastic.co/learn-from-home',
    category: 'education searchimplementation elastik',
  },
  {
    id: 549,
    name: 'Lightbend',
    description: 'Free Full Platform Access: Includes courses about reactive systems design and explores technologies such as Scala and Akka.',
    validity: 'June 30',
    link: 'https://www.lightbend.com/academy/register/0010h00001eEJDIAA4',
    category: 'education testing bigdata',
  },
  {
    id: 550,
    name: 'Osherove Bundle',
    description: '11 Free Development Courses: Includes courses on various facets of software development such as unit testing and continuous delivery.',
    validity: 'NA',
    link: 'https://courses.osherove.com/p/covid-all-in-free-learning-bundle',
    category: 'education fullstack',
  },
  {
    id: 551,
    name: 'Osmosis',
    description: '3-Week Free Platform Access: Includes resources on a wide variety of medical subjects.',
    validity: 'NA',
    link: 'https://www.osmosis.org/covid-19/raisethelinepledge',
    category: 'education medicine doctors',
  },
  {
    id: 552,
    name: 'Calm',
    description: '3-Month Free Access: Includes audio-lesson on meditation, mindfulness, and relaxation.',
    validity: 'NA',
    link: 'https://www.calm.com/kleenex',
    category: 'health fitness yoga',
  },
  {
    id: 553,
    name: 'Headspace',
    description: 'Free sample of meditation program. Valid in USA.',
    validity: 'NA',
    link: 'https://www.headspace.com/covid-19',
    category: 'health fitness yoga',
  },
  {
    id: 554,
    name: 'AHREFS',
    description: 'Free Blogging For Business course. All videos are free.',
    validity: 'NA',
    link: 'https://ahrefs.com/academy/blogging-for-business',
    category: 'others productivity marketing management',
  },
  {
    id: 555,
    name: 'Ancestry',
    description: 'Free access to 500 million records and images for genealogy research',
    validity: 'NA',
    link: 'https://blogs.ancestry.com/ancestry/2020/03/24/free-at-home-education-resources-from-ancestry-and-access-to-nearly-500m-national-archives-records/',
    category: 'others',
  },
  {
    id: 556,
    name: 'Core Power Yoga',
    description: 'Free pre-recorded online classes.',
    validity: 'NA',
    link: 'https://www.corepoweryogaondemand.com/keep-up-your-practice',
    category: 'health fitness workout',
  },
  {
    id: 557,
    name: 'Gold’s Gym',
    description: 'Free access to GOLD’s AMP (App).',
    validity: 'May 31',
    link: 'https://www.goldsgym.com/anywhere/?click_referral=home-vid',
    category: 'health fitness workout',
  },
  {
    id: 558,
    name: 'Peloton',
    description: 'Try the Peloton App free for 90 days.',
    validity: 'NA',
    link: 'https://www.onepeloton.com/app',
    category: 'health fitness workout',
  },
  {
    id: 559,
    name: 'Nike',
    description: 'Access to NTC Premium (App) for free.',
    validity: 'NA',
    link: 'https://news.nike.com/news/nike-digital-health-activity-resources',
    category: 'health fitness workout',
  },
  {
    id: 560,
    name: 'Loom',
    description: 'Loom Pro free for Education. Extended to 30-days Trial. Loom Pro 50% off and extended trial. ',
    validity: 'July 1',
    link: 'https://www.loom.com/blog/coronavirus-response',
    category: 'productivitytools',
  },
  // changed 561 to 603 as it was unavailable
  {
    id: 603,
    name: 'Google',
    description: 'Hangouts Meet Premium for all G Suite customers.',
    validity: 'July 1',
    link: 'https://gsuiteupdates.googleblog.com/2020/03/enabling-hangouts-meet-premium-features.html',
    category: 'productivitytool googlemeet hangouts videocall',
  },
  {
    id: 562,
    name: 'Airtable',
    description: 'Free Airtable Pro for students mutual aid projects.',
    validity: 'NA',
    link: 'https://blog.airtable.com/airtables-support-for-covid-19-response-efforts/',
    category: 'productivitytools',
  },
  {
    id: 563,
    name: 'Atlassian',
    description: 'Free access to Jira and Confluence for small teams. Maximum team size of 10 people.',
    validity: 'NA',
    link: 'https://www.atlassian.com/blog/announcements/atlassian-cloud-remote-friendly-tools-free-small-teams',
    category: 'productivity bitbucket business devops',
  },
  {
    id: 564,
    name: 'Calendly',
    description: 'Free Zoom and GoToMeetings integrations	',
    validity: 'NA',
    link: 'https://blog.calendly.com/meeting-integration-update/',
    category: 'productivity calender',
  },
  {
    id: 565,
    name: 'Shopify',
    description: '14-days trial extended to 90-day free trial.',
    validity: 'NA',
    link: 'https://www.shopify.in/covid19',
    category: 'productivity onlinestore ecommerce e-commerce business covid19',
  },
  {
    id: 566,
    name: 'Amazon',
    description: '2 months of Kindle Unlimited for free.',
    validity: 'June 30',
    link: 'https://www.amazon.com/kindle-dbs/promoLanding?linkCode=w61&imprToken=SD1PvcoQAl3nCLJQjeqTdw&slotNum=0&campaignId=907ea992-8e47-45f1-bacf-eeee592e4423&promoCode=907ea992-8e47-45f1-bacf-eeee592e4423&tag=nypost-20&tag=nypost-20&mod=article_inline',
    category: 'entertainment usa reading books',
  },
  {
    id: 567,
    name: 'Amazon',
    description: '60 day trial period to Comixology Unlimited (Comics Reader).',
    validity: 'NA',
    link: 'https://www.amazon.com/kindle-dbs/cu/signup?tag=mashable-editpost-20&ascsubtag=07svzXPUtzSpOFrLTO3iPv6',
    category: 'entertainment kindle reading books novels',
  },
  {
    id: 568,
    name: 'Scribd',
    description: 'Free access to Scribd’s library for 30 days.',
    validity: 'NA',
    link: 'https://blog.scribd.com/home/2020/3/17/a-letter-from-the-scribd-ceo-to-our-community',
    category: 'entertainment reading books journals',
  },
  // changed 569 to 124
  {
    id: 124,
    name: 'Audible',
    description: 'Free access to selected stories.',
    validity: 'NA',
    link: 'https://www.audible.com/about/newsroom/stories-help-audible-stories-lets-anyone-anywhere-listen-for-free/',
    category: 'entertainment audio amazon',
  },
  {
    id: 570,
    name: 'Minecraft',
    description: 'Free educational content in Minecraft Marketplace.',
    validity: 'NA',
    link: 'https://www.minecraft.net/en-us/article/free-educational-content-minecraft-marketplace-',
    category: 'entertainment education',
  },
  {
    id: 571,
    name: 'GOG',
    description: 'Free access to 27 games.',
    validity: 'NA',
    link: 'https://www.gog.com/partner/stay_at_home',
    category: 'entertainment',
  },
  {
    id: 572,
    name: 'Century',
    description: 'FREE English, maths and science courses during school closure',
    validity: 'NA',
    link: 'https://www.century.tech/explore-century/parents/',
    category: 'education kids children mathematics',
  },
  {
    id: 573,
    name: 'Epic Games',
    description: 'Mega Sale on Major Games like GTA 5 Premium Edition, etc.',
    validity: 'NA',
    link: 'https://www.epicgames.com/store/en-US/',
    category: 'entertainment freegames',
  },
  {
    id: 574,
    name: 'Swayam',
    description: 'An initiative by the government of India to provide the educational material used by IIT\'s and NIT\'s.',
    validity: 'NA',
    link: 'https://swayam.gov.in/',
    category: 'education government india iit nit iisc nptel',
  }


];